### PR TITLE
Create SFT servers in two groups

### PR DESCRIPTION
**Pull request by akshaymankar**
This can be used for deploying new versions without taking out the previous versions.
https://github.com/zinfra/backend-issues/issues/1562
Please merge only after merging https://github.com/wireapp/ansible-sft/pull/28 and updating requirements.yaml.

### CODE REVIEW

**Review by jschaul — APPROVED** [review]
Didn't try it out, but looks good.

**Comment by jschaul** [comment]
So the workflow is: change list of green and blue in terraform. Apply terraform and re-generate inventory. Then run ansible. ? Maybe it would be nice to document that procedure, too.

**Comment by akshaymankar** [comment]
> So the workflow is: change list of green and blue in terraform. Apply terraform and re-generate inventory. Then run ansible. ?

Slightly different. Now that we don't want to be creating/deleting instances that often. Putting things in terraform would be a one time thing (it can of course be modified later). Changing stuff on the VMs to determine which group is active and what version on SFT goes to what group would be the only things necessary before running ansible. We will add some documentation on operating SFT instances.

**Comment by akshaymankar** [comment]
@jschaul I wrote some docs about operating the SFT servers. Can you please read them once before I merge this.

**Review by jschaul — APPROVED** [review]
Thanks for the detailed procedure!

**Pull request merged**
