### PR TITLE
Make the update.sh script take a _path_ instead of a _name_

### PR DESCRIPTION
**Pull request by arianvp**
This means I can do:

`/bin/update.sh charts/wire-se<TAB>`  and it auto-completes to the right
chart name, which saves me 10 seconds per day and makes me not have to
know a chart name apriori. I think the UX is a lot better, as we get
free completion of what charts are available

Not a really important change, just something that made things a bit easier for me when working with these scripts interactively

### CODE REVIEW

**Comment by arianvp** [comment]
Are there any other scripts we use internally that depend on this script that might break because of this?

**Comment by jschaul** [comment]
> Are there any other scripts we use internally that depend on this script that might break because of this?

I don't think so, I did a quick grep, didn't find anything.

But actually I noticed in this repo `bin/sync.sh` uses it, so the path there should be adjusted before merging.

**Comment by arianvp** [comment]
@jschaul oould we look at that script together tomorrow?  It's a bit daunting to me :)

**Comment by jschaul** [comment]
@arianvp please merge :)

**Pull request merged**
