### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by zebot**
Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by smatting** [comment]
@flokli I was wondering about the purpose of this PR. I guess it's convenience PR in case someone wants to bump nixpkgs they can just merge it? Wouldn't this PR also fill up our cachix cache quickly?

**Comment by flokli** [comment]
> @flokli I was wondering about the purpose of this PR. I guess it's convenience PR in case someone wants to bump nixpkgs they can just merge it? Wouldn't this PR also fill up our cachix cache quickly?

There's no reason not to stay up to date on nixpkgs, so yes, we should review and merge this one (and the following PRs).

**Comment by flokli** [comment]
This is right now failing due to https://github.com/Juniper/jxmlease/issues/26 (which is a dependency of ansible)

**Comment by flokli** [comment]
https://github.com/NixOS/nixpkgs/pull/164430 was merged, which disables the `jxmlease` unit tests, working around https://github.com/Juniper/jxmlease/issues/26.

**Pull request merged**
