### PR TITLE
Remove domain name

### PR DESCRIPTION
**Pull request by julialongtin**
remove issuance of a default search domain via the AWS dhcp servers. breaks dns lookup inside of k8s.

### CODE REVIEW

**Comment by akshaymankar** [comment]
Why is zebot committing to this branch?

**Comment by lucendio** [comment]
> Why is zebot committing to this branch?

My bet, [rebases](https://github.com/wireapp/wire-server-deploy/pull/338/commits) GH is not able to recognize as such. I have seen this before.

**Review by lucendio — APPROVED** [review]

**Review by akshaymankar — CHANGES_REQUESTED** [review]
I see that those two commits are on master, but not on develop. I think @julialongtin branched off from master. IMO these two commits shouldn't go to develop.

**Comment by julialongtin** [comment]
republished.

**Review by akshaymankar — APPROVED** [review]

**Pull request merged**
