### PR TITLE
k8s: Install system-coredump in all nodes FS-345

### PR DESCRIPTION
**Pull request by smatting**
Internal issue https://wearezeta.atlassian.net/browse/FS-346

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

### CODE REVIEW

**Review by flokli — CHANGES_REQUESTED** [review]
While this seems to work collecting coredumps, the offline package needs to be extended to also provide the packages.

From the CI output:

```
TASK [Install systemd-coredump] ************************************************
fatal: [kubenode-generous-shiner]: FAILED! => {"changed": false, "msg": "No package matching 'systemd-coredump' is available"}
fatal: [kubenode-ruling-lizard]: FAILED! => {"changed": false, "msg": "No package matching 'systemd-coredump' is available"}
fatal: [kubenode-good-guppy]: FAILED! => {"changed": false, "msg": "No package matching 'systemd-coredump' is available"}
```

**Comment by flokli** [comment]
This still fails, this time due to unmet package dependencies. Seems currently the list of packages isn't sane?

```
systemd-coredump : Depends: systemd (= 237-3ubuntu10.50) but 237-3ubuntu10.52 is to be installed
```
Full log:
```
fatal: [kubenode-clear-orca]: FAILED! => {"cache_update_time": 1642513888, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"      install 'systemd-coredump'' failed: E: Unable to correct problems, you have held broken packages.\n", "rc": 100, "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n systemd-coredump : Depends: systemd (= 237-3ubuntu10.50) but 237-3ubuntu10.52 is to be installed\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " systemd-coredump : Depends: systemd (= 237-3ubuntu10.50) but 237-3ubuntu10.52 is to be installed"]}
```

**Comment by smatting** [comment]
This didn't help. Still fails with:
```
Depends: systemd (= 237-3ubuntu10.50) but 237-3ubuntu10.52 is to be installed
```
I'm a bit puzzled, because as of today https://packages.ubuntu.com/bionic/systemd shows that `bionic` ships `237-3ubuntu10.50`, not `237-3ubuntu10.52`

**Comment by flokli** [comment]
I retriggered the pipeline another time, as it was run 20h ago, but debugging apt package resolution really isn't my cup of tea either :disappointed:

**Comment by smatting** [comment]
I checked `sytemd` versions to figure out where this `237-3ubuntu10.52` is coming from.

`bionic main binary-amd64` has `Version: 237-3ubuntu10`
`bionic-security main binary-amd64` `237-3ubuntu10.50`
`bionic-updates main binary-amd64` `237-3ubuntu10.53` <- this is close to `237-3ubuntu10.52`, but `bionic-updates` wasn't included before https://github.com/wireapp/wire-server-deploy/pull/534/commits/32ee75888b7d0f5a95a8d9017e8f0dbe0a30d071

(source https://gist.github.com/smatting/d7af4ca1443e854078eee777b7edd900)
Also grepping for `237-3ubuntu10.52` yields no results.

**Comment by smatting** [comment]
I inspected the `debs` dump that is generated by `mirror-apt debs` command: It does not contain `systemd` with version `237-3ubuntu10.52` or any package that contains the string `237-3ubuntu10.52`. (`find debs -name '*.deb' | xargs -n 1 dpkg -I | less`).

**Comment by smatting** [comment]
I'm beginning to suspect that the `kubernetes.yaml` ansible playbook doesn't use the offline mirror when installing the offline deployment. @julialongtin

**Comment by smatting** [comment]
> I'm beginning to suspect that the `kubernetes.yaml` ansible playbook doesn't use the offline mirror when installing the offline deployment. @julialongtin

@flokli can we check this theory together?

**Comment by flokli** [comment]
I did a quick look, `terraform/examples/wire-server-deploy-offline-hetzner/main.tf` definitely disables outgoing internet traffic, and `ansible/setup-offline-sources.yml` configures another apt repository:

```ansible
    - name: Register offline repo key
      apt_key:
        url: "{{ ubuntu_repo_gpgkey }}"
        state: present
    - name: Register offline repo
      apt_repository:
        repo: "deb {{ ubuntu_repo_base_url  }} bionic main"
        state: present
```

do we need to add other apt_repositories (not `bionic main`) here?

**Comment by smatting** [comment]
I don't know what else to do here anymore. My motivation for this PR was to install sytem-coredump was for our internal testing environments, which I already applied manually. I could move this change out of the kubernetes playbook to somewhere else which is only applied to our testing environments

**Comment by flokli** [comment]
We changed this to only install systemd-coredump if the `install_systemd_coredump` variable is set to `true` (it defaults to `false`). For this to work, we had to move the `systemd-coredump` stuff into its own role.

**Review by flokli — APPROVED** [review]

**Pull request merged**
