### PR TITLE
Elasticsearch curator

### PR DESCRIPTION
**Pull request by julialongtin**
Deployed on the kubernetes/KVM stack in hetzner.

### CODE REVIEW

**Comment by jschaul** [comment]
It installs fine, whether old data gets deleted I'll only see after 4 days on my cluster (as I set up a fresh cluster). (Feel free to merge).

**Comment by tiago-loureiro** [comment]
@jschaul 

> It installs fine, whether old data gets deleted I'll only see after 4 days on my cluster (as I set up a fresh cluster). (Feel free to merge).

How about now? :)

**Comment by julialongtin** [comment]
I'm hearing from arian that it's deleting 99.99% of the past data, but it's
still retaining some of it. I'm slated to start tearing into what he's
seeing in the morning. in my testing, it correctly curates 100% of logs
after 3 days.

**Comment by jschaul** [comment]
Doesn't work for me:

```
kubectl -n monitoring logs job.batch/monitoring-elasticsearch-curator-1563843600
Found 7 pods, using pod/monitoring-elasticsearch-curator-1563843600-7jdkx
Traceback (most recent call last):
  File "/usr/local/bin/curator", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/curator/cli.py", line 213, in cli
    run(config, action_file, dry_run)
  File "/usr/local/lib/python3.6/site-packages/curator/cli.py", line 117, in run
    action_config = get_yaml(action_file)
  File "/usr/local/lib/python3.6/site-packages/curator/utils.py", line 53, in get_yaml
    cfg = yaml.load(raw)
  File "/usr/local/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/local/lib/python3.6/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python3.6/site-packages/yaml/composer.py", line 43, in get_single_node
    event.start_mark)
yaml.composer.ComposerError: expected a single document in the stream
  in "<unicode string>", line 2, column 1:
    actions:
    ^
but found another document
  in "<unicode string>", line 23, column 1:
    ---
    ^
         
```

(and checking kibana, all logs since the beginning of the cluster are still there).

**Pull request merged**
