### PR TITLE
Feature/simple bootstrap

### PR DESCRIPTION
**Pull request by jschaul**
Trying things out: a ~~simple~~ easy-to-type bootstrap procedure (from ubuntu to a kubernetes cluster - could be extended, possibly). This downloads a bash script which downloads a docker alternative (since kubespray removes any running docker image during installation), and uses that to run the quay.io/wire/networkless-admin image. Within that image, it creates a host file and uses that to install kubernetes to the host system.

Is this a good approach? A bad approach? Should more work be added here? Or are other alternatives better/faster? Thoughts @tiago-loureiro ?

Precedure:

# Installing kubernetes on ubuntu

1. log onto a server running ubuntu 16.04 or 18.04. Make sure it has at least 4 CPUs and at least 8 GB RAM.
2. become root: `sudo su -`
3. Run this init script:

```
curl -sSfL https://raw.githubusercontent.com/wireapp/wire-server-deploy/feature/simple-bootstrap/bin/bootstrap/init.sh > init.sh && chmod +x init.sh && ./init.sh
```

This should take ~20 minutes and give you a kubernetes installation on that server.

### CODE REVIEW

**Comment by jschaul** [comment]
(Note that this could also work just as well to install cassandra and/or other databases to that local host - it's one line added to `inside.sh`)

**Comment by R4m4n** [comment]
This is really helping, but getting this error:
```
fatal: [kubenode01 -> <servers IP>]: FAILED! => {"attempts": 5, "changed": true, "cmd": ["/usr/local/bin/kubeadm", "--kubeconfig", "/etc/kubernetes/admin.conf", "token", "create"], "delta": "0:01:15.023530", "end": "2019-09-26 13:44:45.309834", "msg": "non-zero return code", "rc": 1, "start": "2019-09-26 13:43:30.286304", "stderr": "timed out waiting for the condition", "stderr_lines": ["timed out waiting for the condition"], "stdout": "", "stdout_lines": []}
```

```
kubenode01                 : ok=310  changed=13   unreachable=0    failed=1   
localhost                  : ok=1    changed=0    unreachable=0    failed=0 
```

**Comment by jschaul** [comment]
@R4m4n It's hard to know what's going on without more context. You mentioned in a previous issue that you have some networking setup that lead to a problem with connecting to dl.k8s.io. Possibly this is also a networking issue. Feel free to re-run the script a second time. Otherwise, you'll need to try to execute the command manually and look at logs. Maybe `journalctl -u kubelet -e -f` will show something useful, if kubelet is already running at this point. Maybe run `/usr/local/bin/kubeadm --kubeconfig /etc/kubernetes/admin.conf token create` manually to see why it fails.

**Comment by R4m4n** [comment]
`journalctl -u kubelet -e -f`, this one gives empty logs.
`/usr/local/bin/kubeadm --kubeconfig /etc/kubernetes/admin.conf token create`, this generates a token.

And while running 
```
curl -sSfL https://raw.githubusercontent.com/wireapp/wire-server-deploy/feature/simple-bootstrap/bin/bootstrap/init.sh > init.sh && chmod +x init.sh && ./init.sh

```
All the processes are being executed and then getting this error:
```
fatal: [kubenode01]: FAILED! => {"changed": true, "cmd": "/usr/local/bin/kubectl --kubeconfig /etc/kubernetes/admin.conf get ds kube-proxy --namespace=kube-system -o jsonpath='{.spec.template.spec.nodeSelector.beta.kubernetes.io/os}'", "delta": "0:00:00.126283", "end": "2019-09-30 10:47:31.687588", "msg": "non-zero return code", "rc": 1, "start": "2019-09-30 10:47:31.561305", "stderr": "Error from server (NotFound): daemonsets.extensions \"kube-proxy\" not found", "stderr_lines": ["Error from server (NotFound): daemonsets.extensions \"kube-proxy\" not found"], "stdout": "", "stdout_lines": []}
```

**Comment by jschaul** [comment]
@R4m4n try `kubectl get pods --all-namespaces`. Is `kube-proxy` running? Or is there an error / crash loop for some pod? If so, try to get its logs with `kubectl --namespace kube-system logs kube-proxy-<suffix-of-one-pod-name>`

**Comment by jschaul** [comment]
( I will merge this PR, but @R4m4n feel free to keep posting to this thread )

**Comment by R4m4n** [comment]
Sure @jschaul,
And about the hosts.ini file here: https://docs.wire.com/how-to/install/kubernetes-prod.html#how-to-set-up-your-hosts-ini-file
What if we've used different passwords for different VMs or servers.
And also getting a really big error at the end of the process.
`fatal: [kubenode01]: FAILED! => {"attempts": 3, "changed": true, "cmd": ["timeout", "-k", "600s", "600s", "/usr/local/bin/kubeadm", "init", "--config=/etc/kubernetes/kubeadm-config.yaml", "--ignore-preflight-errors=all", "--experimental-upload-certs", "--skip-phases=addon/coredns"], "delta": "0:05:01.441113", "end": "2019-10-01 11:22:13.229300", "failed_when_result": true, "msg": "non-zero return code", "rc": 1, "start": "2019-10-01 11:17:11.788187", "stderr": "\t[WARNING Port-10251]: Port 10251 is in use\n\t[WARNING Port-10252]: Port 10252 is in use\n\t[WARNING FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists\n\t[WARNING FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists\n\t[WARNING FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists\n\t[WARNING IsDockerSystemdCheck]: detected \"cgroupfs\" as the Docker cgroup driver. The recommended driver is \"systemd\". Please follow the guide at https://kubernetes.io/docs/setup/cri/\n\t[WARNING Port-10250]: Port 10250 is in use\nerror execution phase wait-control-plane: couldn't initialize a Kubernetes cluster", "stderr_lines": ["\t[WARNING Port-10251]: Port 10251 is in use", "\t[WARNING Port-10252]: Port 10252 is in use", "\t[WARNING FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists", "\t[WARNING FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists", "\t[WARNING FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists"................` and so on.

**Comment by jschaul** [comment]
@R4m4n thank you for your feedback. We are planning to provide a simpler way to install all of wire-server (hopefully with fewer issues encountered). This will take a bit of time to complete as we have other work getting in the way.

about your specific questions: 

> What if we've used different passwords for different VMs or servers.

You can make use of host_vars, see https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#assigning-a-variable-to-one-machine-host-variables
Generally, for ansible authentication settings, refer to https://docs.wire.com/how-to/install/ansible-authentication.html or the official ansible docs

> Big error (...) Port 10250 is in use

It seems something is already running on that server, perhaps try with a fresh VM? Or try uninstalling other things listening on that port? You can see what process is listening on certain ports with `sudo netstat -antlp | grep LISTEN`, for instance.

As I said before, if it doesn't work for you, we'll hopefully provide an easier setup in the coming weeks.

**Pull request merged**
