### PR TITLE
Remove dynamodb setting

### PR DESCRIPTION
**Pull request by arianvp**
Not needed anymore

### CODE REVIEW

**Comment by jmatsushita** [comment]
Wouldn't we want to keep dynamoDB settings commented out as documentation if this is an example file?

**Comment by arianvp** [comment]
that's what I am doing here no?

**Comment by jmatsushita** [comment]
Indeed it is 😓

**Review by jmatsushita — APPROVED** [review]

**Comment by arianvp** [comment]
The CI error is a known flake. GPG is my nemesis and I have no idea why sometimes it is convinced the private key isn't there. It happens once every 20 times on my computer as well 🤷🏾

**Comment by jmatsushita** [comment]
Oh yeah, I saw that one before :/ Please go ahead and merge 👍

**Pull request merged**
